In [2]:
import numpy as np

array = np.random.randint(0,10,(3,5))
print(array)

[[9 6 7 7 4]
 [5 4 9 7 5]
 [5 7 4 6 7]]


In [3]:
print(np.max(array), np.argmax(array))

9 0


In [5]:
print(np.max(array,axis =0), np.argmax(array, axis =0))

[9 7 9 7 7] [0 2 1 0 2]


In [6]:
print(np.max(array, axis = 1), np.argmax(array, axis =1))

[9 9 7] [0 2 1]


In [7]:
array_ashraf = np.random.randint(7,52,(5,5))
print(array_ashraf)

[[40 19 39 15 35]
 [27 12 21 36 41]
 [ 9 28 26 37 46]
 [43 36 30  8 33]
 [18 30 25  7  8]]


In [9]:
print(np.max(array_ashraf), np.argmax(array_ashraf))

46 14


In [10]:
print(np.min(array_ashraf), np.argmin(array_ashraf))

7 23
